"""Compile + exec for AOTAutograd's generated runtime-wrapper source.

AOTAutograd codegens its runtime wrappers -- the RuntimeWrapper orchestration,
input-mutation and output-alias epilogues, tensor-subclass unwrap/rewrap, dedup,
synthetic-base, functionalized RNG, effect tokens, and the forward/backward
function bodies -- as Python source. They all funnel through
``_compile_and_exec_source`` here, which compiles and execs the source and
returns the named function. ``capture_generated_wrappers`` is a supported hook to
observe every wrapper (subclass-related or not) as it is generated.
"""

from __future__ import annotations

import contextlib
import functools
import logging
from collections.abc import Callable, Iterator

import torch


log = logging.getLogger(__name__)


# Observers registered via ``capture_generated_wrappers`` are notified, in
# registration order, of every runtime wrapper generated by AOTAutograd. This is a
# supported extension point for tools (e.g. torch.precompile) that want to re-emit
# the generated wrapper source rather than scrape it.
_GENERATED_WRAPPER_OBSERVERS: list[Callable[..., None]] = []


@contextlib.contextmanager
def capture_generated_wrappers(
    observer: Callable[[str, str, str, dict[str, object], Callable[..., object]], None],
) -> Iterator[None]:
    """Register ``observer`` for the duration of the context.

    ``observer(artifact_name, source, fn_name, globals_dict, fn)`` is called for
    each runtime wrapper compiled by ``_compile_and_exec_source`` while active --
    across all wrapper kinds, not just the subclass ones.
    """
    _GENERATED_WRAPPER_OBSERVERS.append(observer)
    try:
        yield
    finally:
        _GENERATED_WRAPPER_OBSERVERS.remove(observer)


def _compile_and_exec_source(
    source: str,
    globals_dict: dict[str, object],
    fn_name: str,
    artifact_name: str,
    wrapped_fn: Callable[..., object] | None = None,
) -> Callable[..., object]:
    """Compile generated source, exec it, and return the named function.

    If wrapped_fn is provided, applies functools.update_wrapper so that
    __wrapped__ and __dict__ (e.g. _fx_graph_cache_key) propagate to the
    generated function.
    """
    if log.isEnabledFor(logging.DEBUG):
        log.debug("Generated %s:\n%s", artifact_name, source)

    torch._logging.trace_structured(
        "artifact",
        metadata_fn=lambda: {
            "name": artifact_name,
            "encoding": "string",
        },
        payload_fn=lambda: source,
    )

    # Use a path under torch/_functorch/ so the code object is recognized by
    # dynamo's MOD_SKIPLIST. The eval frame hook stays active during the entire
    # torch.compile(fn)(*args) call (to handle graph breaks and resume functions),
    # so codegen'd functions called during backward get intercepted even though
    # no tracing is active. A real path makes them skip automatically.
    code = compile(source, f"{__file__}:codegen({artifact_name})", "exec")
    local_dict: dict[str, object] = {}
    exec(code, globals_dict, local_dict)
    fn = local_dict[fn_name]
    if wrapped_fn is not None:
        functools.update_wrapper(fn, wrapped_fn)  # type: ignore[arg-type]
    for observer in _GENERATED_WRAPPER_OBSERVERS:
        observer(artifact_name, source, fn_name, globals_dict, fn)
    return fn  # type: ignore[return-value]
